pkic/pkic.org

content/bylaws.md
This change update bylaws to clarify member eligibility and includes a missing newline in section 8.
=> Update bylaws to clarify member eligibility

content/members/davidgroup.md, data/members/davidgroup.yaml
DAVID GROUP initial profile for PKI Consortium member request.
Thanks <3
=> Add DAVID GROUP as a member

content/wg/pqc/charter.md
The current charter does not match the charter sent out on the mailing list on 2023-06-22
=> Update charter.md with the proposed charter from mailing list

data/members/posdigicert.yaml
Automatically generated pull request to add profile for Pos Digicert Sdn Bhd according to application pkic/members#262.
This closes pkic/members#262
=> Add profile for Pos Digicert Sdn Bhd

data/members/tilaka.yaml
Automatically generated pull request to add profile for Tilaka Nusa Teknologi according to application pkic/members#261.
This closes pkic/members#261
=> Add profile for Tilaka Nusa Teknologi

data/members/trustgatedigital.yaml
Automatically generated pull request to add profile for Trustgate Digital Ltd according to application pkic/members#254.
This closes pkic/members#254
=> Add profile for Trustgate Digital Ltd

data/members/mtg.yaml
Automatically generated pull request to add profile for MTG AG according to application pkic/members#221.
This closes pkic/members#221
=> Add profile for MTG AG

data/members/sunnic-sec.yaml
Automatically generated pull request to add profile for Sunnic Pte Ltd according to application pkic/members#226.
This closes pkic/members#226
=> Add profile for Sunnic Pte Ltd

data/members/compumatica.yaml
Automatically generated pull request to add profile for Compumatica secure networks bv according to application pkic/members#241.
This closes pkic/members#241
=> Add profile for Compumatica secure networks bv

data/members/unsungltd.yaml
Automatically generated pull request to add profile for Unsung Limited according to application pkic/members#236.
This closes pkic/members#236
=> Add profile for Unsung Limited

data/members/quantumgateway.yaml
Automatically generated pull request to add profile for Quantum Gateway Solutions BV according to application pkic/members#225.
This closes pkic/members#225
=> Add profile for Quantum Gateway Solutions BV

data/members/i-314.yaml
Automatically generated pull request to add profile for I-314 S.A. according to application pkic/members#208.
This closes pkic/members#208
=> Add profile for I-314 S.A.

data/members/litmuslogic.yaml
Automatically generated pull request to add profile for Litmus Logic according to application pkic/members#200.
This closes pkic/members#200
=> Add profile for Litmus Logic

content/members/data-warehouse.md, data/members/data-warehouse.yaml, data/members/datawh.yaml
Automatically generated pull request to add profile for Data-Warehouse GmbH according to application pkic/members#207.
This closes pkic/members#207
=> Add profile for Data-Warehouse GmbH

data/members/secondfactor.yaml
Automatically generated pull request to add profile for Second Factor, Inc. according to application pkic/members#188.
This closes pkic/members#188
=> Add profile for Second Factor, Inc.

data/members/savis.yaml
Automatically generated pull request to add profile for SAVIS TECHNOLOGY GROUP according to application pkic/members#184.
This closes pkic/members#184
=> Add profile for SAVIS TECHNOLOGY GROUP

data/members/itida.yaml
Automatically generated pull request to add profile for ITIDA according to application pkic/members#187.
This closes pkic/members#187
=> Add profile for ITIDA

data/members/grcpath.yaml
Automatically generated pull request to add profile for GRC PATH according to application pkic/members#278.
This closes pkic/members#278
=> Add profile for GRC PATH

README.md
To use submodules you first have to run the init command
=> Add `git submodule init` 

data/members/coeia-ksu.yaml, data/members/ksu.yaml
Automatically generated pull request to add profile for COEIA according to application pkic/members#245.
This closes pkic/members#245
=> Add profile for COEIA

content/members/GlobalSign.md, content/members/globalsign.md
=> Create GlobalSign profile page content

data/members/smartcryptosolutions.yaml
Automatically generated pull request to add profile for SmartCrypto according to application pkic/members#253.
This closes pkic/members#253
=> Add profile for SmartCrypto

data/members/digitalsignature.yaml
Automatically generated pull request to add profile for Bangla Phone Limited according to application pkic/members#252.
This closes pkic/members#252
=> Add profile for Bangla Phone Limited

data/members/icp.yaml
Automatically generated pull request to add profile for Federal Authority for Identity, Citizenship, Customs & Port Security (ICP) according to application pkic/members#288.
This closes pkic/members#288
=> Add profile for Federal Authority for Identity, Citizenship, Customs & Port Security (ICP)

data/members/dohatec-ca.yaml
Automatically generated pull request to add profile for Dohatec New Media according to application pkic/members#238.
This closes pkic/members#238
=> Add profile for Dohatec New Media

data/members/dastorllc.yaml
Automatically generated pull request to add profile for DāSTOR according to application pkic/members#293.
This closes pkic/members#293
=> Add profile for DāSTOR

data/members/emudhra.yaml
Add eMudhra member to the PQC working group.
=> update emudhra wg membership

data/members/zenithtec.yaml
Automatically generated pull request to add profile for ZenithTec Solutions according to application pkic/members#259.
This closes pkic/members#259
=> Add profile for ZenithTec Solutions

data/members/soluti.yaml
Automatically generated pull request to add profile for Soluti Negócios Inteligentes Ltda according to application pkic/members#270.
This closes pkic/members#270
=> Add profile for Soluti Negócios Inteligentes Ltda

data/members/cloudsecuriti.yaml
Automatically generated pull request to add profile for Cloud Security Solutions according to application pkic/members#298.
This closes pkic/members#298
=> Add profile for Cloud Security Solutions

data/members/antic.yaml, data/members/camgovca.yaml
Automatically generated pull request to add profile for ANTIC according to application pkic/members#224.
This closes pkic/members#224
=> Add profile for ANTIC

data/members/joaorodolfo.yaml, data/members/wordpress.yaml
Automatically generated pull request to add profile for Cyber Security Specialist into Bank in Brazil according to application pkic/members#223.
This closes pkic/members#223
=> Add profile for Cyber Security Specialist into Bank in Brazil

data/members/appviewx.yaml, data/members/citi.yaml, data/members/multicert.yaml, data/members/pkisolutions.yaml, data/members/secondfactor.yaml
Update membership for members participating in the TCWG
=> Update memberships for TCWG

data/members/swisssign.yaml
Automatically generated pull request to add profile for SwissSign AG according to application pkic/members#316.
This closes pkic/members#316
=> Add profile for SwissSign AG

data/members/deloitte.yaml
Automatically generated pull request to add profile for Deloitte-India according to application pkic/members#297.
This closes pkic/members#297
=> Add profile for Deloitte-India

data/members/eviden.yaml
Automatically generated pull request to add profile for Bull sas according to application pkic/members#322.
This closes pkic/members#322
=> Add profile for Bull sas

data/members/cgi.yaml
Automatically generated pull request to add profile for CGI according to application pkic/members#320.
This closes pkic/members#320
=> Add profile for CGI

data/members/itruzz.yaml
Automatically generated pull request to add profile for ITRUZZ according to application pkic/members#326.
This closes pkic/members#326
=> Add profile for ITRUZZ

data/members/commlinkinfotech.yaml
Automatically generated pull request to add profile for Commlink Info Tech Ltd. according to application pkic/members#314.
This closes pkic/members#314
=> Add profile for Commlink Info Tech Ltd.

data/members/identrust.yaml
Website currently listed is thalesgroup, should be identrust.com
=> Update identrust.yaml website address

data/members/gumushane.yaml
Automatically generated pull request to add profile for Gümüşhane University according to application pkic/members#269.
This closes pkic/members#269
=> Add profile for Gümüşhane University

data/members/sia.yaml
Automatically generated pull request to add profile for SIA according to application pkic/members#358.
This closes pkic/members#358
=> Add profile for SIA

data/members/tm.yaml
Automatically generated pull request to add profile for TM Technology Services Sdn Bhd according to application pkic/members#332.
This closes pkic/members#332
=> Add profile for TM Technology Services Sdn Bhd

data/members/strategicdigitaldefense.yaml
Automatically generated pull request to add profile for Strategic Digital Defense, LLC according to application pkic/members#354.
This closes pkic/members#354
=> Add profile for Strategic Digital Defense, LLC

data/members/conceptsbeyond.yaml
Automatically generated pull request to add profile for Concepts Beyond according to application pkic/members#351.
This closes pkic/members#351
=> Add profile for Concepts Beyond

data/members/devisefutures.yaml
Automatically generated pull request to add profile for Devise Futures - IT Solutions, Lda according to application pkic/members#359.
This closes pkic/members#359
=> Add profile for Devise Futures - IT Solutions, Lda

data/members/consequor.yaml
Automatically generated pull request to add profile for Consequor Tecnologia according to application pkic/members#346.
This closes pkic/members#346
=> Add profile for Consequor Tecnologia

data/members/uva.yaml
Automatically generated pull request to add profile for University of Amsterdam according to application pkic/members#264.
This closes pkic/members#264
=> Add profile for University of Amsterdam

data/members/ambrose.yaml, data/members/btinternet.yaml
Automatically generated pull request to add profile for Ambrose Business Associates **Website**: according to application pkic/members#365.
This closes pkic/members#365
=> Add profile for Ambrose Business Associates **Website**:

data/members/massdata.yaml
Automatically generated pull request to add profile for Mass Data Defense Corporation according to application pkic/members#419.
This closes pkic/members#419
=> Add profile for Mass Data Defense Corporation

data/members/borderlandersinc.yaml
Automatically generated pull request to add profile for Borderlanders Inc according to application pkic/members#423.
This closes pkic/members#423
=> Add profile for Borderlanders Inc

data/members/ctc.yaml
Automatically generated pull request to add profile for Concurrent Technologies Corporation according to application pkic/members#418.
This closes pkic/members#418
=> Add profile for Concurrent Technologies Corporation

data/members/anametric.yaml
Automatically generated pull request to add profile for Anametric, Inc. according to application pkic/members#415.
This closes pkic/members#415
=> Add profile for Anametric, Inc.

data/members/smarttechap.yaml
Automatically generated pull request to add profile for Smart Tech Asia Pacific Sdn Bhd according to application pkic/members#433.
This closes pkic/members#433
=> Add profile for Smart Tech Asia Pacific Sdn Bhd

data/members/renault.yaml
Automatically generated pull request to add profile for Renault Group according to application pkic/members#452.
This closes pkic/members#452
=> Add profile for Renault Group

data/members/incert.yaml
Automatically generated pull request to add profile for INCERT GIE according to application pkic/members#457.
This closes pkic/members#457
=> Add profile for INCERT GIE

data/members/adaptivesystemsinc.yaml
Automatically generated pull request to add profile for Adaptive Systems Inc. according to application pkic/members#409.
This closes pkic/members#409
=> Add profile for Adaptive Systems Inc.

data/members/dal.yaml
Automatically generated pull request to add profile for Dalhousie University according to application pkic/members#393.
This closes pkic/members#393
=> Add profile for Dalhousie University

data/members/0trust.yaml
Automatically generated pull request to add profile for Foard Consulting LLC according to application pkic/members#378.
This closes pkic/members#378
=> Add profile for Foard Consulting LLC

data/members/id-fix.yaml
Automatically generated pull request to add profile for ID-Fix AB according to application pkic/members#377.
This closes pkic/members#377
=> Add profile for ID-Fix AB

data/members/cypher-z.yaml
Automatically generated pull request to add profile for Tsinghua Univeristy according to application pkic/members#317.
This closes pkic/members#317
=> Add profile for Tsinghua Univeristy

data/members/kryptos.yaml
Automatically generated pull request to add profile for Cyber Quanta / Kryptos according to application pkic/members#462.
This closes pkic/members#462
=> Add profile for Cyber Quanta / Kryptos

data/members/protonmail.yaml, data/members/tqn.yaml
Automatically generated pull request to add profile for Tasmanian Quantum Network Quantum Safe Transition Working Group according to application pkic/members#369.
This closes pkic/members#369
=> Add profile for Tasmanian Quantum Network Quantum Safe Transition Working Group

data/members/optinetz.yaml
Automatically generated pull request to add profile for Optinetz LImited according to application pkic/members#387.
This closes pkic/members#387
=> Add profile for Optinetz LImited

data/members/ankatech.yaml
Automatically generated pull request to add profile for AnkaTech according to application pkic/members#473.
This closes pkic/members#473
=> Add profile for AnkaTech

data/members/medtronic.yaml
Automatically generated pull request to add profile for Medtronic according to application pkic/members#472.
This closes pkic/members#472
=> Add profile for Medtronic

data/members/cisco.yaml
Automatically generated pull request to add profile for Cisco Systems according to application pkic/members#437.
This closes pkic/members#437
=> Add profile for Cisco Systems

data/members/chase.yaml
Automatically generated pull request to add profile for JP Morgan according to application pkic/members#424.
This closes pkic/members#424
=> Add profile for JP Morgan

data/members/nowquantum.yaml
Automatically generated pull request to add profile for NowQuantum according to application pkic/members#383.
This closes pkic/members#383
=> Add profile for NowQuantum

data/members/think-secure.yaml
Automatically generated pull request to add profile for Think Secure according to application pkic/members#479.
This closes pkic/members#479
=> Add profile for Think Secure

data/members/dictalabs.yaml
Automatically generated pull request to add profile for DictaLabs LLC according to application pkic/members#486.
This closes pkic/members#486
=> Add profile for DictaLabs LLC

data/members/securetron.yaml
Automatically generated pull request to add profile for Securetron according to application pkic/members#491.
This closes pkic/members#491
=> Add profile for Securetron

data/members/sonicai.yaml
Automatically generated pull request to add profile for Sonic AI according to application pkic/members#494.
This closes pkic/members#494
=> Add profile for Sonic AI

data/members/uber.yaml
Automatically generated pull request to add profile for Uber according to application pkic/members#355.
This closes pkic/members#355
=> Add profile for Uber

data/members/arict.yaml
Automatically generated pull request to add profile for Arict according to application pkic/members#509.
This closes pkic/members#509
=> Add profile for Arict

data/members/twca.yaml
Automatically generated pull request to add profile for TAIWAN-CA Inc. according to application pkic/members#517.
This closes pkic/members#517
=> Add profile for TAIWAN-CA Inc.

data/members/kquantaresearch.yaml
Automatically generated pull request to add profile for Kquanta Research LlP according to application pkic/members#519.
This closes pkic/members#519
=> Add profile for Kquanta Research LlP

data/members/savyint.yaml
Automatically generated pull request to add profile for Savyint Group according to application pkic/members#532.
This closes pkic/members#532
=> Add profile for Savyint Group

data/members/ngkore.yaml
Automatically generated pull request to add profile for NgKore according to application pkic/members#534.
This closes pkic/members#534
=> Add profile for NgKore

data/members/shreeojas.yaml
Automatically generated pull request to add profile for Shree Ojas system and techinfra Pvt Ltd. according to application pkic/members#538.
This closes pkic/members#538
=> Add profile for Shree Ojas system and techinfra Pvt Ltd.
